const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";
CONSTANTS.ENDPOINT.TODO = "/todo";

CONSTANTS.ENDPOINT.TODOID = "/todo/:id";

CONSTANTS.ENDPOINT.LOGIN = "/login";

CONSTANTS.ENDPOINT.SIGNUP = "/signup";

module.exports = CONSTANTS;
